### ISSUE TITLE
Problem with tap detection in iOS PlatformNavBar?

### ISSUE THREAD

**Issue by mlava** [aqwert/flutter_platform_widgets#182]
Hi all,
I hope this question isn't too simple, but I've been trying to days and can't seem to make it work!

I have replaced Scaffold and BottomNavigationBar with PlatformScaffold and PlatformNavBar.

Detection of taps works as expected on Android but not on iOS emulator. Swiping left or right moves the page and PlatformNavBar properly in both Android and iOS. It just isn't getting taps in iOS.

Tap events are captured as expected using the native flutter BottomNavigationBar but not with PlatformNavBar.

My code is below. I don't know if this is a bug or I've implemented incorrectly. I would truly appreciate any help!

```
class _MyHomePageState extends State<MyHomePage> {
  int _selectedTabIndex = 0;

  List<BottomNavigationBarItem> buildBottomNavBarItems() {
    return [
      BottomNavigationBarItem(
        icon: Icon(context.platformIcons.addCircledOutline),
        title: Text('Calculators'),
        backgroundColor: Colors.blue,
      ),
      BottomNavigationBarItem(
        icon: Icon(context.platformIcons.checkMarkCircledOutline),
        title: Text('Diag. Criteria'),
        backgroundColor: Colors.blue,
      ),
      BottomNavigationBarItem(
        icon: Icon(context.platformIcons.settings),
        title: Text('Normal Ranges'),
        backgroundColor: Colors.blue,
      ),
      BottomNavigationBarItem(
        icon: Icon(context.platformIcons.favoriteSolid),
        title: Text('Favourites'),
        backgroundColor: Colors.blue,
      ),
      BottomNavigationBarItem(
        icon: Icon(context.platformIcons.dehaze),
        title: Text('More'),
        backgroundColor: Colors.blue,
      )
    ];
  }

  @override
  Widget build(BuildContext context) {
    return PlatformScaffold(
      //iosContentPadding: true,
      appBar: PlatformAppBar(
        title: Text(widget.title),
      ),
      body: buildPageView(),
      bottomNavBar: PlatformNavBar(
        currentIndex: _selectedTabIndex,
        itemChanged: (index) => setState(() {bottomTapped(index);},),
        items: buildBottomNavBarItems(),),
    );
  }

  PageController pageController = PageController(
    initialPage: 0,
    keepPage: true,
  );

  Widget buildPageView() {
    return PageView(
      controller: pageController,
      onPageChanged: (index) {
        pageChanged(index);
      },
      children: <Widget>[
        Calculators(),
        DiagnosticCriteria(),
        NormalRanges(),
        Favourites(),
        More(),
      ],
    );
  }

  @override
  void initState() {
    super.initState();
  }

  void pageChanged(int index) {
    setState(() {
      _selectedTabIndex = index;
    });
  }

  void bottomTapped(int index) {
    setState(() {
      _selectedTabIndex = index;
      pageController.animateToPage(
          index, duration: Duration(milliseconds: 500), curve: Curves.ease);
    });
  }
}
```

The 'Run' output is as below:

```
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
ScrollController attached to multiple scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 111 pos 12: '_positions.length == 1'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:111:12)
#3      PageController.animateToPage (package:flutter/src/widgets/page_view.dart:203:41)
#4      _MyHomePageState.bottomTapped.<anonymous closure> (package:flutterapp1/main.dart:156:22)
#5      State.setState (package:flutter/src/widgets/framework.dart:1233:30)
#6      _MyHomePageState.bottomTapped (package:flutterapp1/main.dart:154:5)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#ee57c
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(199.2, 563.8)
  finalLocalPosition: Offset(31.0, 38.7)
  button: 1
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by mlava** [comment]
My mistake, just bad coding... Sorry

**Comment by chentianxin** [comment]
> My mistake, just bad coding... Sorry

I also encountered the same error, how did you solve it. Thank you

**Comment by Drolegc** [comment]
I'm having the same issue and I cant figure it out how to solve it.

Here's my code

```
class LobbyScreen extends StatelessWidget {
  LobbyScreen({Key? key}) : super(key: key);
  final PageController _pageController = PageController();

  @override
  Widget build(BuildContext context) {
    return RepositoryProvider(
      create: (_) => PoolRepository(PoolApi()),
      child: Builder(builder: (_) {
        return BlocProvider(
          create: (context) =>
              LobbyCubit(RepositoryProvider.of<PoolRepository>(context))
                ..getCategoriesWithPools(),
          child: PlatformScaffold(
              material: (_, __) =>
                  MaterialScaffoldData(resizeToAvoidBottomInset: false),
              cupertino: (_, __) =>
                  CupertinoPageScaffoldData(resizeToAvoidBottomInset: false),
              bottomNavBar: PlatformNavBar(
                itemChanged: _goToPage,
                items: const [
                  BottomNavigationBarItem(
                    label: "Home",
                    icon: Icon(Icons.home),
                  ),
                  BottomNavigationBarItem(
                    label: "My pools",
                    icon: Icon(Icons.monetization_on),
                  )
                ],
              ),
              body: SafeArea(
                  child: PageView(
                    controller: _pageController,
                      physics: const NeverScrollableScrollPhysics(),
                      children: const [LobbyHome(), MyPools()]))),
        );
      }),
    );
  }

  void _goToPage(int index) {
    _pageController.jumpToPage(index);
    return;
    _pageController.animateToPage(index,
        duration: const Duration(milliseconds: 200), curve: Curves.easeInOut);
  }
}
```

**Comment by Drolegc** [comment]
> > My mistake, just bad coding... Sorry
> 
> I also encountered the same error, how did you solve it. Thank you
> 
> ```
> 
> ════════ Exception caught by gesture ═══════════════════════════════════════════
> The following assertion was thrown while handling a gesture:
> ScrollController attached to multiple scroll views.
> 'package:flutter/src/widgets/scroll_controller.dart':
> Failed assertion: line 109 pos 12: '_positions.length == 1'
> 
> 2
> 
> Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
> In either case, please report this assertion by filing a bug on GitHub:
>   https://github.com/flutter/flutter/issues/new?template=2_bug.md
> 
> When the exception was thrown, this was the stack
> #2      ScrollController.position
> package:flutter/…/widgets/scroll_controller.dart:109
> #3      RawScrollbarState.getScrollbarDirection
> package:flutter/…/widgets/scrollbar.dart:927
> #4      RawScrollbarState.handleThumbPressStart
> package:flutter/…/widgets/scrollbar.dart:950
> #5      _CupertinoScrollbarState.handleThumbPressStart
> package:flutter/…/cupertino/scrollbar.dart:161
> #6      RawScrollbarState._gestures.<anonymous closure>.<anonymous closure>
> package:flutter/…/widgets/scrollbar.dart:1086
> ...
> Handler: "onLongPressStart"
> Recognizer: _ThumbPressGestureRecognizer#3f979
>     debugOwner: _CupertinoScrollbarState#cc712(tickers: tracking 2 tickers)
>     state: possible
> ```

How did you solve it? Plz
